# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5ad34a033157ee5bce93f44d5d9975f73cf6cf1972b7dc7c1d1f2b58b9af3cbaa95147ba8a446254b5f104b60167d6503276a3b776852cedb68a69dd8d44d92

test:
  secret_key_base: 32aad03276cc964165af0e56c06422c13beab834bf2023d364873f5a111730bafa87a0115f01e715170ae6476ce6669975fdacc9b04259fb684cc6f88334101a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
